# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/kevin/Documents/CS585

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/kevin/Documents/CS585

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/kevin/Documents/CS585/CMakeFiles /home/kevin/Documents/CS585/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/kevin/Documents/CS585/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named CS585

# Build rule for target.
CS585: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 CS585
.PHONY : CS585

# fast build rule for target.
CS585/fast:
	$(MAKE) -f CMakeFiles/CS585.dir/build.make CMakeFiles/CS585.dir/build
.PHONY : CS585/fast

#=============================================================================
# Target rules for targets named gtest

# Build rule for target.
gtest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gtest
.PHONY : gtest

# fast build rule for target.
gtest/fast:
	$(MAKE) -f CMakeFiles/gtest.dir/build.make CMakeFiles/gtest.dir/build
.PHONY : gtest/fast

#=============================================================================
# Target rules for targets named square

# Build rule for target.
square: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 square
.PHONY : square

# fast build rule for target.
square/fast:
	$(MAKE) -f CMakeFiles/square.dir/build.make CMakeFiles/square.dir/build
.PHONY : square/fast

game.m.o: game.m.cpp.o
.PHONY : game.m.o

# target to build an object file
game.m.cpp.o:
	$(MAKE) -f CMakeFiles/CS585.dir/build.make CMakeFiles/CS585.dir/game.m.cpp.o
.PHONY : game.m.cpp.o

game.m.i: game.m.cpp.i
.PHONY : game.m.i

# target to preprocess a source file
game.m.cpp.i:
	$(MAKE) -f CMakeFiles/CS585.dir/build.make CMakeFiles/CS585.dir/game.m.cpp.i
.PHONY : game.m.cpp.i

game.m.s: game.m.cpp.s
.PHONY : game.m.s

# target to generate assembly for a file
game.m.cpp.s:
	$(MAKE) -f CMakeFiles/CS585.dir/build.make CMakeFiles/CS585.dir/game.m.cpp.s
.PHONY : game.m.cpp.s

src/testing/gtest.o: src/testing/gtest.cpp.o
.PHONY : src/testing/gtest.o

# target to build an object file
src/testing/gtest.cpp.o:
	$(MAKE) -f CMakeFiles/gtest.dir/build.make CMakeFiles/gtest.dir/src/testing/gtest.cpp.o
.PHONY : src/testing/gtest.cpp.o

src/testing/gtest.i: src/testing/gtest.cpp.i
.PHONY : src/testing/gtest.i

# target to preprocess a source file
src/testing/gtest.cpp.i:
	$(MAKE) -f CMakeFiles/gtest.dir/build.make CMakeFiles/gtest.dir/src/testing/gtest.cpp.i
.PHONY : src/testing/gtest.cpp.i

src/testing/gtest.s: src/testing/gtest.cpp.s
.PHONY : src/testing/gtest.s

# target to generate assembly for a file
src/testing/gtest.cpp.s:
	$(MAKE) -f CMakeFiles/gtest.dir/build.make CMakeFiles/gtest.dir/src/testing/gtest.cpp.s
.PHONY : src/testing/gtest.cpp.s

src/testing/square.o: src/testing/square.cpp.o
.PHONY : src/testing/square.o

# target to build an object file
src/testing/square.cpp.o:
	$(MAKE) -f CMakeFiles/square.dir/build.make CMakeFiles/square.dir/src/testing/square.cpp.o
.PHONY : src/testing/square.cpp.o

src/testing/square.i: src/testing/square.cpp.i
.PHONY : src/testing/square.i

# target to preprocess a source file
src/testing/square.cpp.i:
	$(MAKE) -f CMakeFiles/square.dir/build.make CMakeFiles/square.dir/src/testing/square.cpp.i
.PHONY : src/testing/square.cpp.i

src/testing/square.s: src/testing/square.cpp.s
.PHONY : src/testing/square.s

# target to generate assembly for a file
src/testing/square.cpp.s:
	$(MAKE) -f CMakeFiles/square.dir/build.make CMakeFiles/square.dir/src/testing/square.cpp.s
.PHONY : src/testing/square.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... CS585"
	@echo "... edit_cache"
	@echo "... gtest"
	@echo "... rebuild_cache"
	@echo "... square"
	@echo "... test"
	@echo "... game.m.o"
	@echo "... game.m.i"
	@echo "... game.m.s"
	@echo "... src/testing/gtest.o"
	@echo "... src/testing/gtest.i"
	@echo "... src/testing/gtest.s"
	@echo "... src/testing/square.o"
	@echo "... src/testing/square.i"
	@echo "... src/testing/square.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

